website:
    title: 'Tropical Island'
    https: false
    view: App/Views
    controller: App/Controllers
    routes: Routes
    publickey: 6LfN_cEZAAAAAOUJe4_WVBNm_lRz4TxHg_Jru21V
    privatekey: 6LfN_cEZAAAAAMZNEgyfnuA8ByWjiFW42fE_EsSM
    discord: https://discord.com/api/webhooks/811558031560671263/Dbzt9zB6mSKeUTG8xp3MRvUR-poXUYtVd0tsk-XDAol_FKa1GRFh6AhqIrSPJRhyWEN5
    max_ingame_accounts: 10
    rates:
        exp: 1000
        penya: 100
        drop: 100
    sidebar:
        user_online: true
        user_peak: true
database:
    server: 62.141.36.118\SQLEXPRESS
    username: Venom
    password: AtlantisVenom2021
    account_dbf: ACCOUNT_DBF
    character_dbf: CHARACTER_01_DBF
    logging_dbf: LOGGING_01_DBF
    website_dbf: BETA_DBF
    item_dbf: ITEM_DBF
server:
    salt: kikugalanet
    ip: 127.0.0.1
    port: '5600'
shop:
    param1: qoidjoasjd32380
    param2: '0'
    max_shoppingcard: 10
security:
    admin: Z
    gamemaster: G
    user: F
vote:
    reward: 10
